import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import TokenBalance from '../components/TokenBalance';

const Home: NextPage = () => {
  const baseTokenAddress: `0x${string}` = '0x7475fa4c36344f1d633964f02564f37162299194';
  const tokenDecimals = 18; // Replace with the token's decimals

  return (
    <div className={styles.container}>
      <Head>
        <title>$SHIBUSSY Connect Wallet</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <TokenBalance tokenAddress={baseTokenAddress} tokenDecimals={tokenDecimals} />

      </main>
    </div>
  );
};

export default Home;
